name: Test E2E pool

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        type: [linux, windows]
    runs-on: [self-hosted, '${{ matrix.type }}', '1ES.Pool=e2e-pool']

    steps:
      - uses: actions/checkout@v3

      - name: Run test
        run: |
          echo "Hello, world!"
          echo "I'm running on a ${{ matrix.type }} agent"