name: E2E (GitHub-main)

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - devops/e2e/**

jobs:
  version:
    name: Set version
    runs-on: ubuntu-latest
    outputs:
      tweak: ${{ steps.version.outputs.tweak }}
    steps:
      - name: Set version
        id: version
        run: echo "::set-output name=tweak::$(echo $(date +'%Y%m%d%H%M'))"

  package:
    uses: ./.github/workflows/package-build.yml
    needs: version
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu18.04, ubuntu20.04, debian9]
        variant:
          [
            { arch: arm, platform: linux/arm/v7 },
            { arch: arm64, platform: linux/arm64/v8 },
            { arch: amd64, platform: linux/amd64 },
          ]
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.variant.arch }}
      platform: ${{ matrix.variant.platform }}
      tweak: ${{ needs.version.outputs.tweak }}

  fetch-targets:
    name: Fetch Test Targets
    needs: package
    uses: ./.github/workflows/e2etest-fetch-targets.yml
    with:
      environment: e2e-github-main
    secrets: inherit

  provision-hub:
    name: Provision IoT Hub
    uses: ./.github/workflows/e2etest-provision-hub.yml
    needs:
      - fetch-targets
    with:
      environment: e2e-github-main
      resourceGroupName: ${{ needs.fetch-targets.outputs.resourceGroupName }}
    secrets: inherit

  provision-ais:
    name: Create Device Identities
    uses: ./.github/workflows/e2etest-provision-ais.yml
    needs:
      - provision-hub
      - fetch-targets
    with:
      environment: e2e-github-main
      resourceGroupName: ${{ needs.fetch-targets.outputs.resourceGroupName }}
      distroName: ${{ needs.fetch-targets.outputs.distroName }}
    secrets: inherit

  provision-hosts:
    name: Provision Host VM
    uses: ./.github/workflows/e2etest-provision-hosts.yml
    needs:
      - provision-ais
      - provision-hub
      - fetch-targets
    with:
      environment: e2e-github-main
      resourceGroupName: ${{ needs.fetch-targets.outputs.resourceGroupName }}
      distroName: ${{ needs.fetch-targets.outputs.distroName }}
    secrets: inherit

  run-tests:
    name: Run Tests
    uses: ./.github/workflows/e2etest-run-tests.yml
    needs:
      - fetch-targets
      - provision-hosts
    with:
      environment: e2e-github-main
      resourceGroupName: ${{ needs.fetch-targets.outputs.resourceGroupName }}
      distroName: ${{ needs.fetch-targets.outputs.distroName }}
      cpuThreshold: 50
      testNameSuffix: (github-main)
    secrets: inherit

  deprovision-resources:
    name: Deprovision Cloud Resources
    if: always()
    runs-on: ubuntu-latest
    environment: e2e-github-main
    needs:
      - fetch-targets
      - provision-hub
      - provision-hosts
      - run-tests

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete resource group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group delete --name ${{ needs.fetch-targets.outputs.resourceGroupName }} --yes --no-wait