name: Package

on:
  push:
    # branches:
    #   - main
    # paths:
    #   - src/**

jobs:
  package:
    uses: ./.github/workflows/build-package.yml
    with:
      artifact: test
      os: '["ubuntu20.04"]'
      variant: '[{"arch": "amd64", "platform": "linux/amd64"}]'
      signed: true
    secrets: inherit