name: Package

on:
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  version:
    name: Set version
    runs-on: ubuntu-latest
    outputs:
      tweak: ${{ steps.version.outputs.tweak }}
    steps:
      - name: Set version
        id: version
        run: echo "::set-output name=tweak::$(echo $(date +'%Y%m%d%H%M'))"

  package:
    name: Package
    uses: ./.github/workflows/package-build.yml
    needs: version
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu18.04, ubuntu20.04, debian9]
        variant:
          [
            { arch: arm, platform: linux/arm/v7 },
            { arch: arm64, platform: linux/arm64/v8 },
            { arch: amd64, platform: linux/amd64 },
          ]
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.variant.arch }}
      platform: ${{ matrix.variant.platform }}
